### ISSUE TITLE
help

### ISSUE THREAD

**Issue by skidders** [wgpsutherland/slack-connect-4-bot#12]
I installed it in heroku using the button. Put in the API token then deployed. It says successful. I tried to run it in slack, nothing happens. Help

**Comment by wgpsutherland** [comment]
Hey @skidders thanks for getting in touch. This issue did not happen the last time I ran the code a few months ago, however I was able to replicate it myself when I created a new deployment just now, and I've pushed a fix for it. So if you just make a new deployment it should work perfectly. Thanks again.
