### ISSUE TITLE
2nd game

### ISSUE THREAD

**Issue by skidders** [wgpsutherland/slack-connect-4-bot#13]
I installed this using heroku. Tested it in slack. I typed in @connectfour start. Nobody responded since it was still a test. Then put it in our games channel. Tried it there and it stopped working. The command doesn't do anything anymore. Should I just reinstall it? Because I could do it but then what if someone starts it and no one answer, will this happen again?

**Comment by wgpsutherland** [comment]
This is the response you should receive if nobody responds to the request to play a game:
<img width="534" alt="screen shot 2016-12-16 at 12 22 03" src="https://cloud.githubusercontent.com/assets/5879966/21262637/5de391c4-c38a-11e6-91fc-2961ddd1a952.png">
There shouldn't be any issues with people not responding, and it's not related to people not responding to the games request as I've just tested it out on the current build. You may be having the issue where the Heroku dyno has gone to sleep? If so, go into the app dashboard on the Heroku website and restart all the dynos and it should come back online:
<img width="1280" alt="screen shot 2016-12-16 at 12 25 05" src="https://cloud.githubusercontent.com/assets/5879966/21262751/e263e282-c38a-11e6-8a1b-e108ae2bad1f.png">

**Comment by wgpsutherland** [comment]
To add to my previous comment, is it failing to respond when it is saying it is online on Slack (green dot next to the name)?
<img width="280" alt="screen shot 2016-12-16 at 12 28 39" src="https://cloud.githubusercontent.com/assets/5879966/21262825/47d83f64-c38b-11e6-97e3-bdf523788393.png">

**Comment by skidders** [comment]
Yes, you suggestion works. And also I just notice it was offline. I guess I
need to make sure it is online. Thanks for the quick response. I appreciate it.

**Comment by nlogozzo** [comment]
Easier Way: what you can also do is type the app name from heroku .herokuapp.com (EX: connect4.herokuapp.com) and your bot will come online

**Comment by wgpsutherland** [comment]
@nlogozzo thanks! I'll add it to the docs
