### ISSUE TITLE
No way to abort a game?

### ISSUE THREAD

**Issue by ndebard** [wgpsutherland/slack-connect-4-bot#14]
Seems like if  you're in the middle of the game and want to stop it, perhaps someone leaves or gets mad at the spam and you move the bot to another channel - there doesn't seem to be a way to "@connect4: abort" or "@connect4: stop".

**Comment by wgpsutherland** [comment]
@ndebard thanks for suggesting this improvement - I've just implemented it.
Simply type `quit` to abandon the current game. Please let me know if there are any issues.
