### ISSUE TITLE
Compact theme offsets first line of board

### ISSUE THREAD

**Issue by joshfarrant** [wgpsutherland/slack-connect-4-bot#5]
When using the compact theme in Slack the first line of the Connect 4 Board is offset by the bot's username.

![connect-4](https://cloud.githubusercontent.com/assets/6840861/10424552/e12c3e30-70c7-11e5-8ff8-e19451e176c0.png)

A possible fix could be starting the message with a new line character, if that's possible, or just a single character on the first line, followed by a line break.

**Comment by wgpsutherland** [comment]
Thanks for bringing this to my attention!

**Comment by joshfarrant** [comment]
No problem. Great job on the game! 😃
