### ISSUE TITLE
It is possible to have a game playing yourself

### ISSUE THREAD

**Issue by joshfarrant** [wgpsutherland/slack-connect-4-bot#6]
Not sure if this is intended or not , but you can start a game, respond 'yes' twice, and play yourself. Not sure if this is enabled for testing purposes, or a bug.

![connect-4-bug-2](https://cloud.githubusercontent.com/assets/6840861/10430101/45406d7e-70f5-11e5-8116-e62842f3a5a7.png)

**Comment by wgpsutherland** [comment]
This is intentional behaviour, like you said, for testing purposes.
